# Generated by Django 3.1.1 on 2020-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='категория')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128, unique=True, verbose_name='артикул')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='цена')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='заголовок страницы (<title>)')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='pyshop.Category', verbose_name='категории')),
                ('related_products', models.ManyToManyField(blank=True, to='pyshop.Product', verbose_name='связанные продукты')),
            ],
        ),
    ]
